apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::327562857081:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::327562857081:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-XATSHG4C70QF
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-12-14T19:57:38Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
    manager: vpcLambda
    operation: Update
    time: "2021-12-14T19:57:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1297"
  uid: 448c82ec-a0b8-4d10-a251-518fd79de9f6
